spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.meditrack.notification.dto.AppointmentCreatedEventDto

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans