server:
  port: 9000

spring:
  profiles:
    default: local
  application:
    name: auth-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    prometheus:
      access: unrestricted