spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meditrack_authserver
    username: meditrack_user
    password: meditrack123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  issuer: http://localhost:9000

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

