spring:
  datasource:
    url: jdbc:postgresql://appointment-db:5432/meditrack_appointmentservice
    username: meditrack_user
    password: meditrack123
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0    #This is for Zipkin to sample all the requests. In production, you might want to set this to a lower value to reduce overhead.
    propagation:
      type: b3

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


